using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using TaxCalculatorAPI.Services.Models;

namespace TaxCalculatorAPI.Documents
{
    public class TaxCertificateDocument : IDocument
    {
        public TaxCertificateData Data { get; }

        public TaxCertificateDocument(TaxCertificateData data)
        {
            Data = data;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(50);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12).FontFamily("Arial"));

                page.Header()
                    .Text($"South African Tax Certificate - Tax Year {Data.TaxYear}")
                    .SemiBold().FontSize(18).FontColor(Colors.Blue.Medium).AlignCenter();

                page.Content()
                    .PaddingVertical(10)
                    .Column(column =>
                    {
                        column.Item().Text($"Full Name: {Data.FullName}").Bold();
                        column.Item().Text($"Tax Reference Number: {Data.TaxReferenceNumber ?? "N/A"}");
                        column.Item().Text($"Date Issued: {Data.DateIssued:dd MMM yyyy}");
                        column.Item().Text($"Issuer: {Data.IssuerName} ({Data.IssuerContact})");
                        column.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        column.Item().Text("Income Details").Bold().FontSize(14); // Removed PaddingBottom as it is not supported  
                        column.Item().Text($"- Monthly Salary: R{Data.MonthlySalary:N2}");
                        column.Item().Text($"- Annual Bonus: R{Data.AnnualBonus:N2}");
                        column.Item().Text($"- Retirement Annuity Contributions: R{Data.RetirementAnnuityContributions:N2}");
                        column.Item().Text($"- Medical Tax Credits: R{Data.MedicalTaxCredits:N2}");

                        column.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        column.Item().Text("Tax Calculation").Bold().FontSize(14); // Removed PaddingBottom as it is not supported  
                        column.Item().Text($"- Taxable Income: R{Data.TaxableIncome:N2}");
                        column.Item().Text($"- Total Tax Payable: R{Data.TotalTaxPayable:N2}");
                        column.Item().Text($"- Monthly Tax: R{Data.MonthlyTax:N2}");

                        column.Item().PaddingVertical(10).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        column.Item().Text("Declaration").Italic();
                        column.Item().Text("I hereby declare that the information provided in this certificate is true and correct to the best of my knowledge.");
                        column.Item().PaddingTop(40).AlignCenter().Text("_________________________");
                        column.Item().AlignCenter().Text("Authorized Signature");
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(x => x.Span("Generated by Your Company Tax Calculator").FontSize(10).FontColor(Colors.Grey.Medium));
            });
        }
    }
}
